// Generated by gencpp from file robo_msgs/Pendulum.msg
// DO NOT EDIT!


#ifndef ROBO_MSGS_MESSAGE_PENDULUM_H
#define ROBO_MSGS_MESSAGE_PENDULUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robo_msgs
{
template <class ContainerAllocator>
struct Pendulum_
{
  typedef Pendulum_<ContainerAllocator> Type;

  Pendulum_()
    : pred_dt(0.0)
    , pos()
    , flag_y(0)  {
    }
  Pendulum_(const ContainerAllocator& _alloc)
    : pred_dt(0.0)
    , pos(_alloc)
    , flag_y(0)  {
  (void)_alloc;
    }



   typedef double _pred_dt_type;
  _pred_dt_type pred_dt;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef int32_t _flag_y_type;
  _flag_y_type flag_y;





  typedef boost::shared_ptr< ::robo_msgs::Pendulum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robo_msgs::Pendulum_<ContainerAllocator> const> ConstPtr;

}; // struct Pendulum_

typedef ::robo_msgs::Pendulum_<std::allocator<void> > Pendulum;

typedef boost::shared_ptr< ::robo_msgs::Pendulum > PendulumPtr;
typedef boost::shared_ptr< ::robo_msgs::Pendulum const> PendulumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robo_msgs::Pendulum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robo_msgs::Pendulum_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robo_msgs::Pendulum_<ContainerAllocator1> & lhs, const ::robo_msgs::Pendulum_<ContainerAllocator2> & rhs)
{
  return lhs.pred_dt == rhs.pred_dt &&
    lhs.pos == rhs.pos &&
    lhs.flag_y == rhs.flag_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robo_msgs::Pendulum_<ContainerAllocator1> & lhs, const ::robo_msgs::Pendulum_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robo_msgs::Pendulum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robo_msgs::Pendulum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_msgs::Pendulum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robo_msgs::Pendulum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_msgs::Pendulum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robo_msgs::Pendulum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robo_msgs::Pendulum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3387e721239562d2b53a348be4d1547";
  }

  static const char* value(const ::robo_msgs::Pendulum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3387e721239562dULL;
  static const uint64_t static_value2 = 0x2b53a348be4d1547ULL;
};

template<class ContainerAllocator>
struct DataType< ::robo_msgs::Pendulum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robo_msgs/Pendulum";
  }

  static const char* value(const ::robo_msgs::Pendulum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robo_msgs::Pendulum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pred_dt\n"
"geometry_msgs/Point pos\n"
"int32 flag_y\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::robo_msgs::Pendulum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robo_msgs::Pendulum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pred_dt);
      stream.next(m.pos);
      stream.next(m.flag_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pendulum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robo_msgs::Pendulum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robo_msgs::Pendulum_<ContainerAllocator>& v)
  {
    s << indent << "pred_dt: ";
    Printer<double>::stream(s, indent + "  ", v.pred_dt);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    s << indent << "flag_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flag_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBO_MSGS_MESSAGE_PENDULUM_H
