# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robo_msgs/Pendulum.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Pendulum(genpy.Message):
  _md5sum = "c3387e721239562d2b53a348be4d1547"
  _type = "robo_msgs/Pendulum"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 pred_dt
geometry_msgs/Point pos
int32 flag_y
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['pred_dt','pos','flag_y']
  _slot_types = ['float64','geometry_msgs/Point','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pred_dt,pos,flag_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Pendulum, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pred_dt is None:
        self.pred_dt = 0.
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      if self.flag_y is None:
        self.flag_y = 0
    else:
      self.pred_dt = 0.
      self.pos = geometry_msgs.msg.Point()
      self.flag_y = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4di().pack(_x.pred_dt, _x.pos.x, _x.pos.y, _x.pos.z, _x.flag_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.pred_dt, _x.pos.x, _x.pos.y, _x.pos.z, _x.flag_y,) = _get_struct_4di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4di().pack(_x.pred_dt, _x.pos.x, _x.pos.y, _x.pos.z, _x.flag_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pos is None:
        self.pos = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.pred_dt, _x.pos.x, _x.pos.y, _x.pos.z, _x.flag_y,) = _get_struct_4di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4di = None
def _get_struct_4di():
    global _struct_4di
    if _struct_4di is None:
        _struct_4di = struct.Struct("<4di")
    return _struct_4di
